export const SIZE = {
  PHONE_UPPER_BOUNDARY: 600,
  TABLET_UPPER_BOUNDARY: 900,
  TABLET_LANDSCAPE_UPPER_BOUNDARY: 1200,
  DESKTOP_UPPER_BOUNDARY: 1800,
}

export const DEVICE = {
  PHONE_ONLY: `(max-width: ${SIZE.PHONE_UPPER_BOUNDARY - 1}px)`,
  TABLET_DOWN: `(max-width: ${SIZE.TABLET_LANDSCAPE_UPPER_BOUNDARY}px)`,
  TABLET_ONLY: `(min-width: ${SIZE.PHONE_UPPER_BOUNDARY}px) and (max-width: ${
    SIZE.TABLET_LANDSCAPE_UPPER_BOUNDARY
  }px)`,
  DESKTOP_ONLY: `(min-width: ${SIZE.TABLET_LANDSCAPE_UPPER_BOUNDARY}px)`,
}
