import { COLORS } from "../config"

export const PRIMARY_BACKGROUND_COLOR = COLORS.PRIMARY_BACKGROUND_COLOR
export const PRIMARY_FOREGROUND_COLOR = COLORS.PRIMARY_FOREGROUND_COLOR

export const PRIMARY_TEXT_COLOR = COLORS.PRIMARY_TEXT_COLOR
export const LINK_BACKGROUND_COLOR = COLORS.LINK_BACKGROUND_COLOR

// Generics
export const BLACK = "#000"
